version: '3.9'


services:
  neko_bot:
    image: ghcr.io/nitekot/neko_bot:main
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN_CHAT=${BOT_ADMIN_CHAT}
      - DB_URL=postgresql+asyncpg://postgres:${PG_USER_PASSWORD}@db:5432/cookie_db

  db:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_DB=cookie_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${PG_USER_PASSWORD}
    ports:
      - 127.0.0.1:${PG_LOCAL_PORT}:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
