version: '3.9'


services:
  neko_bot:
    build:
      context: .
      target: dev
    command: >
      sh -c "pdm migrate && pdm start"
    environment:
      - DEBUG=true
      - BOT_TOKEN=${BOT_TOKEN}
      - BOT_ADMIN_CHAT=${BOT_ADMIN_CHAT}
      - DB_URL=postgresql+asyncpg://postgres:postgres@db:5432/cookie_db
    volumes:
      - ./migrations:/project/migrations

    depends_on:
      - db


  db:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_DB=cookie_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data
