[project]
name = "neko_bot"
version = "0.0.1"
description = ""
authors = [
    {name = "Nitekot", email = "nitekot@gmail.com"},
]
dependencies = [
    "aiogram>=3.1.1",
    "sqlalchemy[asyncio]>=2.0.23",
    "asyncpg>=0.29.0",
]

requires-python = ">=3.11"
readme = "README.md"
license = {text = "MIT"}

[tool.pdm.scripts]
start = "python -m app.bot"
migrate = "alembic upgrade head"

[tool.pdm.dev-dependencies]
dev = [
    "pytest>=7.4.3",
    "pytest-asyncio>=0.21.1",
    "alembic>=1.12.1",
]
