"""init

Revision ID: b65ee2366213
Revises: 
Create Date: 2023-12-01 21:20:08.562452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b65ee2366213'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dialogs',
    sa.Column('id', sa.BIGINT(), nullable=False),
    sa.Column('peer_id', sa.BIGINT(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dialogs_peer_id'), 'dialogs', ['peer_id'], unique=False)
    op.create_table('fsm_state_data',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id', 'chat_id')
    )
    op.create_table('warns',
    sa.Column('user_id', sa.BIGINT(), nullable=False),
    sa.Column('chat_id', sa.BIGINT(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('warned_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False)
    )
    op.create_index('warn_idx', 'warns', ['chat_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('warn_idx', table_name='warns')
    op.drop_table('warns')
    op.drop_table('fsm_state_data')
    op.drop_index(op.f('ix_dialogs_peer_id'), table_name='dialogs')
    op.drop_table('dialogs')
    # ### end Alembic commands ###
