name: Docker

on:
  workflow_dispatch:
  
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:
    name: Build and push Docker image 

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Install the cosign tool except on PR
      # https://github.com/sigstore/cosign-installer
      - name: Install cosign
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@v3.3.0
        with:
          cosign-release: 'v2.2.2'

      # Set up BuildKit Docker container builder to be able to build
      # multi-platform images and export cache
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@f95db51fddba0c2d1ec667646a06c2ce06100226 # v3.0.0

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@343f7c4344506bcbf9b4de18042ae17996df046d # v3.0.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      # Extract metadata (tags, labels) for Docker
      # https://github.com/docker/metadata-action
      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@96383f45573cb7f253c731d3b3ab81c87ef81934 # v5.0.0
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@0565240e2d4ab88bba5387d719585280857ece09 # v5.0.0
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Sign the resulting Docker image digest except on PRs.
      # This will only write to the public Rekor transparency log when the Docker
      # repository is public to avoid leaking data.  If you would like to publish
      # transparency data even for private images, pass --force to cosign below.
      # https://github.com/sigstore/cosign
      - name: Sign the published Docker image
        if: ${{ github.event_name != 'pull_request' }}
        env:
          # https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-an-intermediate-environment-variable
          TAGS: ${{ steps.meta.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
        # This step uses the identity token to provision an ephemeral certificate
        # against the sigstore community Fulcio instance.
        run: echo "${TAGS}" | xargs -I {} cosign sign --yes {}@${DIGEST}

  deploy:
    name: Deploy to Host

    if: github.event_name != 'pull_request'

    needs: build

    runs-on: ubuntu-latest
    environment: production
    permissions:
      contents: read
      packages: read

    env:
      BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
      BOT_ADMIN_CHAT: ${{ secrets.BOT_ADMIN_CHAT }}
      PG_USER_PASSWORD: ${{ secrets.PG_USER_PASSWORD }}
      PG_LOCAL_PORT: ${{ vars.PG_LOCAL_PORT }}
      PANDC_CHAT_ID: ${{ vars.PANDC_CHAT_ID }}
      RULE_URL: ${{ vars.RULE_URL }}
      TOKEN_KEY: ${{ vars.TOKEN_KEY }}
      TOKEN_AUD: ${{ vars.TOKEN_AUD }}
      TOKEN_ISS: ${{ vars.TOKEN_ISS }}
      MAIN_SITE_URL: ${{ vars.MAIN_SITE_URL }}
      DB_URL: postgresql+asyncpg://postgres:${{ secrets.PG_USER_PASSWORD }}@127.0.0.1:5432/cookie_db

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.11.5
          cache: true

      - name: Install dependencies
        run: pdm sync -d

      - name: Setup SSH tunel to host db
        run: |
          mkdir ~/.ssh
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
          eval `ssh-agent -s`
          ssh-add - <<< "${{ secrets.SSH_KEY }}"
          ssh -fnNT -L 5432:127.0.0.1:${{ vars.PG_LOCAL_PORT }} ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }}

      - name: Make migration
        run: pdm migrate

      - name: Pull new image on host and restart bot container
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          envs: BOT_TOKEN,BOT_ADMIN_CHAT,PG_USER_PASSWORD,PG_LOCAL_PORT,PANDC_CHAT_ID,RULE_URL,TOKEN_KEY,TOKEN_AUD,TOKEN_ISS,MAIN_SITE_URL
          script: |
            docker login ${{ env.REGISTRY }} -u ${{ github.actor }} -p ${{ github.token }}
            docker compose pull
            docker compose up -d --no-deps neko_bot
            docker logout ${{ env.REGISTRY }}
